### ISSUE TITLE
Criar um checklist com critérios de avaliação

### ISSUE THREAD

**Issue by leouieda** [leouieda/matematica-especial#21]
Preciso criar uma lista detalhada das coisas que vou avaliar para cada prática. Ex:

```
* Mensagens de commit informativas? sim | não | parcial
* Código final formatado adequadamente? sim | não | parcial
```

Nesse caso, `sim` seria ponto total, `não` seria zero e `parcial` meio ponto.

Colocar essas listas nas práticas ajudaria os alunos a saberem como vou julgar o trabalho. Também ajudaria eu e o @victortxa na correção.

**Comment by leouieda** [comment]
A partir da [aula de sistemas lineares](https://github.com/leouieda/mat-esp-sistema-linear) eu tenho incluido esse checklist nos READMEs:
- [ ] Mensagens de commit que explicam claramente a mudança que foi feita
  [total|parcial|zero] 0.5 pt
- [ ] Formatação do código apropriada.
  Ex: `espacamento = (maximo - minimo)/(N - 1)`,
  `indices = range(0, N, 1)`, `dado = dados[i + 1]` == BOM.
  `espacamento=(maximo-minimo)/ (N-1)`, `indices=range (0,N,1)`,
  `dado= dados [i+ 1]` == RUIM [total|parcial|zero] 0.5 pt
- [ ] Utilizar variáveis ao invés de colocar número "na mão".
  Ex: `for i in range(0, N):`, `A[k][N - 1]` == BOM.
  `for i in range(0, 39):`, `A[k][47]` == RUIM. [total|parcial|zero] 1 pt
- [ ] Código com comentários que explicam "por que" algo foi feito, não só
  "o que" foi feito [total|parcial|zero] 1 pt
- [ ] Nomes de variáveis descritivos. Ex: `temperatura`, `media_por_hora`,
  `linha`, `somatorio` == BOM. `a`, `var`, `meh`, `lista` == RUIM.
  [total|parcial|zero] 2 pt
- [ ] Código produz a solução correta (**exatamente** como especificado em "Resultado esperado") [total|parcial|zero] 5 pt
- [ ] Tarefa bônus [total|parcial|zero] 1 pt extra (não será considerado
  caso a nota já seja 10)
